# Generated by Django 5.0 on 2025-12-08 16:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_chatroom_message'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='moderated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='moderated_by',
            field=models.ForeignKey(blank=True, help_text='Administrator who reviewed this event', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='moderation_notes',
            field=models.TextField(blank=True, help_text='Admin notes about moderation decision', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='moderation_status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', help_text='Status of event moderation review', max_length=20),
        ),
    ]
