# Generated by Django 5.0 on 2025-11-01 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('attendee', 'Attendee'), ('event_organizer', 'Event Organizer')], default='attendee', max_length=20),
        ),
    ]
