# Generated by Django 5.0 on 2025-12-08 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0002_alter_userprofile_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('attendee', 'Attendee'), ('event_organizer', 'Event Organizer'), ('administrator', 'Administrator')], default='attendee', max_length=20),
        ),
    ]
